name: Deploy to npm

on:
  schedule:
    # Daily run
    - cron: "0 4 * * *"
  workflow_dispatch: null

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: npm

      - run: git pull --tags
      - run: npm install
      - run: npm run build
      - run: npm test

      - name: Create packages for .d.ts files
        run: node deploy/createTypesPackages.js

      # Deploy anything which differs from the npm version of a tsconfig
      - name: "Deploy built packages to NPM"
        run: node deploy/deployChangedPackages.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
